services:
  redis:
    image: redis:latest
    container_name: redis
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
  
  web:
    build: .
    container_name: weave
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis

volumes:
  redis_data:
