site_name: Weave
repo_url: https://github.com/matheusfabiao/weave
repo_name: matheusfabiao/weave
edit_uri: tree/main/
site_url: http://localhost:8000/docs/
use_directory_urls: false
docs_dir: docs
site_dir: docs_build

nav:
  - Início: index.md
  - Guia: guide.md
  - Sobre: about.md
  - Aplicativos:
    - Contas: 'apps/accounts.md'
    - Artigos: 'apps/articles.md'
    - Agente de IA: 'apps/ai_agent.md'


theme:
  name: material
  language: pt-BR
  logo: assets/weave-logo.png
  favicon: assets/weave-logo.png
  features:
    - content.code.copy
    - content.code.annotate
  code:
    highlight_theme: dracula
  palette:
    scheme: slate

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: false
  - pymdownx.superfences
